version: "3.7"
services:
  ubuntu:
    image: irasc/drone_robotics:latest
    container_name: ubuntu
    stdin_open: true # Equivalent to -i in docker run
    tty: true # Equivalent to -t in docker run
    volumes:
    - /home/ubuntu/Robotics_vnc/shell:/home/ubuntu/Desktop/shell
    restart: unless-stopped
    ports:
      - "6080:80"
